### ISSUE TITLE
wish: pause animation without clearing traces already drawn

### ISSUE THREAD

**Issue by stewie** [inDigiNeous/GeoKone#1]
As is, animation may be paused either by pressing "p" key or by clicking the "Animation" button while animation is underway. However, when paused/resumed by either of those methods, upon resuming ALL EXISTING TRACES are cleared. I wish ability to just pause (freeze). If this is already possible, I haven't found how to do so.

related:
Each "formation" lives in its own canvas layer, right?
I wish ability to toggle visibility for each individual layer.  (note:  I propose that while a layer is not visible, its animation.) Also (asking for the moon?) separate controls for each layer, providing ability to toggle animation and /or traces for an individual formation, would be hugely helpful.

**Comment by inDigiNeous** [comment]
@stewie This is now implemented, in the github version, coming to next release version probably.
