### ISSUE TITLE
issue: ('traces' drawn from a) deleted formation remain onscreen when formation is deleted

### ISSUE THREAD

**Issue by stewie** [inDigiNeous/GeoKone#2]
If 'Traces' is active/enabled, deleting a formation does not cause it (traces painted by it) to be removed from the canvas.

**Comment by inDigiNeous** [comment]
@stewie Currently how the tracing works it's a flat buffer where all the formations are traced into .. so there is no individual traced layers, so implementing this support is impossible with current model, would require considerable refactoring, closing issue for now.
